export const technologies = [
  { icon: "devicon:java", name: "Java", category: "Language" },
  { icon: "devicon:typescript", name: "TypeScript", category: "Language" },
  { icon: "devicon:python", name: "Python", category: "Language" },
  { icon: "devicon:javascript", name: "JavaScript", category: "Language" },
  { icon: "devicon:react", name: "React", category: "Frontend" },
  { icon: "devicon:nextjs", name: "Next.js", category: "Frontend" },
  { icon: "devicon:angular", name: "Angular", category: "Frontend" },
  { icon: "devicon:spring", name: "Spring Boot", category: "Backend" },
  { icon: "devicon:quarkus", name: "Quarkus", category: "Backend" },
  { icon: "devicon:nodejs", name: "Node.js", category: "Backend" },
  { icon: "devicon:docker", name: "Docker", category: "DevOps" },
  { icon: "devicon:kubernetes", name: "Kubernetes", category: "DevOps" },
  { icon: "devicon:azure", name: "Azure", category: "Cloud" },
  { icon: "devicon:postgresql", name: "PostgreSQL", category: "Database" },
  { icon: "devicon:mysql", name: "MySQL", category: "Database" },
  { icon: "devicon:redis", name: "Redis", category: "Database" },
];
